baseurl = "https://markvoelker.github.io/blog"
languageCode = "en-us"
title = "Future Relics"
theme = "hyde-hyde"
Paginate = 5
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true

[index]
  category = "categories"
  tag = "tags"

[params]
  twitterName = "marktvoelker"
  githubName = "markvoelker"
  linkedinName = "markvoelker"
  hideSidebarIconText = true
  sidebartitle = "Future Relics"
  sidebartagline = "Everything we work on goes obsolete someday--and that's what makes it so much fun."
  description = "Everything we work on goes obsolete someday--and that's what makes it so much fun."

[params.social]
  twitter = "marktvoelker"
  linkedin = "markvoelker"

[[menu.main]]
  name = "RSS"
  url = "/index.xml"

[[menu.social]]
  pre = "<i class='fa fa-twitter'></i>"
  url = "http://www.twitter.com/marktvoelker"
  identifier = "Twitter"

[[menu.social]]
  pre = "<i class='fa fa-linkedin'></i>"
  url = "http://www.linkedin.com/in/markvoelker"
  identifier = "linkedin"

[[menu.footer]]
  name = "Blog"
  url = "/posts"

[[menu.footer]]
  name = "RSS"
  url = "/index.xml"
