---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://markvoelker.github.io/blog"
title: "Technology is Fun Because It's Always Changing"
canonifyurls: true
...
