---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://markvoelker.github.io/futurerelics_blog"
title: "Hugo Test Blog Interface"
canonifyurls: true
...
